# ?? DATABASE ??
spring.datasource.url=jdbc:postgresql://localhost:5432/stockmanagement
spring.datasource.username=postgres
spring.datasource.password=babulis4mpc
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / HIBERNATE ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ?? APP PORT ??
server.port=8080

# ?? APP NAME ??
spring.application.name=stock-management

# JWT
jwt.secret=stockmanagement2026secretkeyforjwtrwanda
jwt.expiration=86400000